ALTER TABLE `booking` 
CHANGE COLUMN `length` `length` FLOAT(20) NULL DEFAULT NULL ,
CHANGE COLUMN `width` `width` FLOAT(20) NULL DEFAULT NULL ,
CHANGE COLUMN `weight` `weight` FLOAT(20) NULL DEFAULT NULL,
CHANGE COLUMN `height` `height` FLOAT(20) NULL DEFAULT NULL ;
