
CREATE TABLE `booking` (
	`id` bigint(20) NOT NULL AUTO_INCREMENT,
	`booking_no` int(10) DEFAULT NULL,
	`customer_id` bigint(20) DEFAULT NULL,
	`customer_name` varchar(225) DEFAULT NULL,
	`contact_person` varchar(225) DEFAULT NULL,
	`department` varchar(225) DEFAULT NULL,
	`department_id` int(20) DEFAULT NULL,
	`address` varchar(775) DEFAULT NULL,
	`area` varchar(225) DEFAULT NULL,
	`mode_of_shipping` tinyint(1) DEFAULT NULL,
	`vehicle_type` int(10) DEFAULT NULL,
	`driver` varchar(255) DEFAULT NULL,
	`driver_id` int(10) DEFAULT NULL,
	`plate_no` varchar(20) DEFAULT NULL,
	`booking_status` tinyint(1) DEFAULT NULL,
	`time_called` varchar(10) DEFAULT NULL,
	`special_instruction` varchar(1000) DEFAULT NULL,
	`date_ready` datetime DEFAULT NULL,
	`document` varchar(10) DEFAULT NULL,
	`weight` decimal(20,5) DEFAULT NULL,
	`length` decimal(20,5) DEFAULT NULL,
	`width` decimal(20,5) DEFAULT NULL,
	`height` decimal(20,5) DEFAULT NULL,
	`status` tinyint(1) DEFAULT '1',
	`created_date` DATETIME DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`),
	UNIQUE KEY `booking_no` (`booking_no`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=latin1;